max_user_messages_per_session: 500
warn_template: "<system>The user can send {remaining} more messages. Use **bold text** to emphasize the warning. Politely warn the user.</system>"
warn_last_message: "<system>This is the final message the assistant will send in this conversation. Use **bold** text to convey this to the user. Say goodbye warmly and invite the user to start a new conversation.</system>"
blocked_message: "ğŸ˜• ×”×’×¢×ª ×œ××¡×¤×¨ ×”×”×•×“×¢×•×ª ×”××¨×‘×™ ×œ×©×™×—×”. ×¨×•×¦×” ×œ×”×ª×—×™×œ ×©×™×—×” ×—×“×©×”?"
non_paying_messages: >
  ×¨×’×¢ ×¨×’×¢â€¦ ×× ×¡×™× ×œ×§×‘×œ ×”××œ×¦×•×ª ××™×©×™×•×ª ×‘×œ×™ ×œ×”×™×•×ª ×× ×•×™×™×?
  ×–×” ×›××• ×œ× ×¡×•×ª ×œ×”×™×›× ×¡ ×œ×¡×¨×˜ ×‘×œ×™ ×›×¨×˜×™×¡ ğŸ¬
  ×”×¦'××˜ ×©×œ× ×• ×©××•×¨ ×œ×× ×•×™×™× ×‘×œ×‘×“ â€“ ××‘×œ ××œ ×“××’×”, ×›×¨×˜×™×¡ ×”×›× ×™×¡×” ×××© ×›××Ÿ: <a href="https://promotion.haaretz.co.il/offers" target="_blank" rel="noopener noreferrer">×œ×”×¦×˜×¨×¤×•×ª ×œ×× ×•×™</a>
long_request: |
  """
  ×•×•××•, ×–×• ×©××œ×” ×¢× ×”×¨×‘×” ×ª×•×›×Ÿ â€“ ×™×•×ª×¨ ×Ö¾200 ××™×œ×™×!
  ×‘×©×‘×™×œ ×©× ×•×›×œ ×œ×”××œ×™×¥ ×œ×š ×¢×œ ××©×”×• ××¢×•×œ×” ×œ×¨××•×ª, × ×¦×˜×¨×š ×©×ª×›×ª×‘×• ×œ× ×• ×‘×§×¦×¨×”:
  ××” ×‘× ×œ×š ×œ×¨××•×ª? ×¡×“×¨×” ××• ×¡×¨×˜? ×–'×× ×¨ ××¡×•×™×? ××¦×‘ ×¨×•×—?
  """"
token_limit: 200
chat_ttl_seconds: 1800 # 30 minutes
